== CUIE Abschlussprojekt

=== Bearbeitet von

* Luca Fluri
* Andreas Ambühl

=== Integriert in die OOP2-Projekte von

* *_Ergänzen Sie hier welche OOP2-Teams Ihr Projekt erfolgreich integriert haben._*


=== Feature-Liste und Tipps für die Integration
* _Was wird ersetzt?_
** Mit unserem BusinessControl "PositionChooser" kann ein/eine OOP2-Student/in die beiden Felder _"Breitengrad" (Latitude)_ und
_"Längengrad" (Longitude)_ ersetzen. Dabei besteht die Möglichkeit, beide Felder zu einem kombinierten Feld
zusammenfügen, oder die Felder separat zu lassen und unseren PositionChooser entsprechend nur in einem der Felder oder
dann dupliziert in beiden Feldern zu implementieren.

* _Boolean "COMPLEX_FIELD" und "DETAILED_DEBUGGING":_
** Am Anfang der Datei "PositionChooser.java" befindet sich zwei boolean Werte, die der /die OOP2-Student/in je nach
gewünschtem Verhalten auf `true` oder `false` setzen kann.
** `COMPLEX_FIELD`: Der Benutzer kann hiermit wählen, ob er in einem Feld *nur* Latitude (oder Longitude) anzeigen und
eingeben möchte, oder *beides* kombiniert.
** `DETAILED_DEBUGGING`: Der Benutzer kann hiermit wählen, ob er ein detaillierteres Logging haben möchte. Zum Beispiel
würde dann im Terminal ausgedruckt, welche Fonts geladen werden oder wie das JSON-Objekt aussieht, welches von der API
zurückgegeben wird beim Klick auf "Auto-Fill").

* _Farben und Farbschema:_
** In den beiden CSS-Dateien positionChooser.css sowie positionChooserDropDown.css kann der/die OOP2-Student/in wie
folgt das Farbschema einfach ändern: Fast zuoberst bei den jeweiligen CSS Dateien gibt es je einen Bereich für die
Farbpalette, markiert mit `* START of color-palette`. Da sind alle verwendeten Farben jeweils zentral aufgelistet. Von
`-base-color` werden später im CSS einige Farb-Varianten abgeleitet.
** Es sind bereits drei verschiedene Farbschemas hinterlegt, zwischen einfach umgeschaltet werden kann, indem man die
entsprechenden Werte (aus-)kommentiert.
** Hinweis: Online-Tools wie https://material.io/resources/color können helfen, ein Farbschema für sich zu finden.

* _Weitere Features:_
** Mittels DropDown-Pfeil eine *Karte* öffnen:
*** Die Karte wird geöffnet und auf die dann bereits allfällig schon vorhandenen
Koordinaten zentriert.
*** Der Benutzer kann die Karte verschieben und zoomen und mittels Klick die Koordinaten neu setzen.
** Mit dem Button "*Autofill*" können automatisch weitere Felder wie Standort, Gemeinde und Kanton ausgefüllt werden,
sofern entsprechende Daten in der Geocoding API verfügbar sind.
*** Der/die OOP2-Student/in kann demzufolge auch ein Binding dieser drei Zusatzfelder vornehmen, falls er möchte.
*** Hinweis: Wir benutzen das API von https://positionstack.com/ für das Reverse Geocoding und 
https://www.openstreetmap.org/ für die Karte.
** Das *Eingabe-Feld* ermöglicht die Eingabe von *unterschiedlichen Formaten* und prüft jeweils die *Validität* dieser
Eingabe. Die Eingabe wird, sobald sie valid ist, sofort übernommen und ua. auf der Karte aktualisiert. Mögliche Eingaben
sind:
*** Latitude, Longitude, zum Beispiel:
**** `47.3459, 8.6605`
**** `47 8`
**** ...
*** GPS Koordinaten (DMS-Format), zum Beispiel:
**** `47° 20' 45.24'' N, 8° 39' 37.8'' E`
**** `47°20'45.24"N,8°39'37.8"E`
**** `47°0'0"N, 8°0'0"E`
**** ...
*** _Hinweise:_
**** Durch Drücken der `ENTER`-Taste wird die Eingabe in das Standard-Format konvertiert, also xx.xxxxx, yy.yyyyy
**** Es spielt keine Rolle, ob Leerzeichen dazwischen sind oder nicht.
**** Das Komma zwischen Breiten-/Längengrad kann wahlweise auch weggelassen werden; dann muss jedoch mindestens ein
Leerzeichen vorhanden sein.
**** Im DMS-Format kann für die Sekunden-Eingabe sowohl das " - Zeichen verwendet werden, wie auch zwei einzelne ' -
Zeichen.
**** Auf https://www.latlong.net kann man einfach einen Ort suchen und erhält dann unter der Karte Lat/Long- oder
GPS-Koordinaten für einfaches Copy/Paste in unseren PositionChooser. Die Lat/Long-Koordinaten erhält man auch einfach via
https://www.openstreetmap.org (mit Rechtsklick -> Adresse anzeigen) oder https://www.google.ch/maps (langer Klick auf
Karte).
**** Die Eingabe von 0 bis 9 Nachkommastellen ist erlaubt.
**** Es wird überprüft, ob "Breitengrad" (Latitude) im erlaubten Bereich von ±90° und ob "Längengrad" (Longitude)" im
erlaubten Bereich von ±180° ist.
** *Fehlermeldung* beim Start:
*** Beim Start vom PositionChooser wird folgende Fehlermeldung gezeigt:
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".` Wir haben viel Zeit investiert, der Ursache dieses
Fehlers nachzugehen und ihn zu beheben und dabei verschiedene Lösungsansätze versucht. Der Fehler wird offenbar von
einer der verwendeten Dependencies verursacht, auf die wir nicht wirklich Einfluss haben. Da dies jedoch die
Funktionsweise der Applikation in keiner Weise beeinträchtigt, haben wir entschieden, diesen Fehler so stehenzulassen.


=== Abgabe

* *Mittwoch, 10.6.2020*, 20:42 Uhr

* Die Abgabe erfolgt durch ein "Push" auf den Master-Branch Ihres GitHub-Repositories.

=== Initiale Schritte

* Tragen Sie ihren Namen unter "Bearbeitet von" ein.

* Benennen Sie das Package `project` um. Verwenden Sie Ihren GitHub-Account- oder Team-Namen. (Via `Refactor -> Rename…`)

* Pushen Sie diese Änderungen am besten sofort ins Git-Repository (z.B. via `VCS -> Commit… -> Commit & Push`)


=== Abschliessende Schritte

* Tragen Sie die Namen der OOP2-Studierenden, die ihr Projekt erfolgreich integriert haben, unter "Integriert in die OOP2-Projekte von" ein


=== Aufgabe: Dashboard oder Business Control für WindparksFX

Entwerfen und implementieren Sie entweder ein Dashboard oder ein Business Control für das OOP2-Projekt 'WindparksFX' auf Basis JavaFX.

Dashboard

* ein Dashboard ersetzt oder ergänzt den sogenannten Header der Windparks-Applikation
* es arbeitet auf mindestens 2 Attributen eines Windparks
* typischerweise enthält es also mehrere interaktive Custom Controls (im Sinne der Vorlesung)

Business Control

* Ein Business Control ersetzt eines (oder mehrere) der im sogenannten Editor-Bereich des OOP2-Projekt verwendeten Standard-TextFields.
* Das Business Control soll den Benutzer beim jeweiligen Arbeitsschritt optimal unterstützen und alle im Unterricht besprochenen Mindestanforderungen an ein Business-Control erfüllen.

Für die einzelnen CustomControls des Dashboards verwenden Sie bei der Implementierung die Struktur wie im package `template_simplecontrol`.

Für das _'Business Control'_ verwenden Sie bei der Implementierung die Struktur wie im package `template_businesscontrol`.

Es ist Bestandteil der Aufgabe das passende Template auszuwählen (und zu erkennen, falls ein Template nicht geeignet ist).

=== Präsentation

* *Montag, 8.6.2020*, 19:45 Uhr, via MS Teams
* Die Projekte werden der OOP2-Klasse im Rahmen einer virtuellen *Poster-Session* präsentiert.
* Die Postersession startet mit Kurzpräsentationen (1 bis 2 Minuten) aller Projekte.
* Danach wird in projekt-spezifischen "Meetings" die Gelegenheit gegeben auf Detailfragen einzugehen.
* Erarbeiten Sie eine geeignete Präsentationsform, so dass das Interesse möglichst vieler OOP2-Teams an Ihrem Projekt geweckt wird.
* Organisieren Sie Integrationstermine mit den interessierten OOP2-Studierenden.
** Die Integration ist eine Gemeinschafts-Aufgabe von CUIE- und OOP2-Team.

=== Bewertung

* Mit einer guten Präsentation Ihres implementierten und lauffähigen Projekts an der Postersession haben Sie normalerweise mindestens eine 4.0 erreicht.
* Durch eine gute Code-Qualität, d.h. insbesondere eine klare Struktur des Codes entsprechend der im Unterricht erarbeiteten Konzepte, können Sie eine 5.0 erreichen.
* Die Qualität aus Benutzersicht durch die Anzahl Integrationen in OOP2-Projekte. Jede Integration wird mit +0.25 bewertet, jedoch maximal mit +1.5.
* *Nicht genügend* ist es
** wenn Sie an der Postersession nicht oder überwiegend passiv teilnehmen.
** falls im vorgestellten Projekt keine der im Unterricht erarbeiteten Konzepte erkennbar sind
** das Projekt nicht compilierfähig ist
** falls es sich um ein Plagiat handelt
** falls kein nennenswerter Beitrag bei der Entwicklung geleistet wurde
** im Zweifelsfall wird ein Code-Walkthrough durchgeführt
* In Ausnahmefällen kann es dazu kommen, dass Teammitglieder unterschiedliche Noten erhalten.


=== Bitte beachten Sie

* Falls Sie das Assignment zu zweit bearbeiten:
** tragen Sie beide Namen unter "Bearbeitet von" ein
** arbeiten Sie ausschliesslich in einem Repository
** falls sie beide Zugang zu diesem Repository wollen: tragen Sie die zweite Person als "Collaborator" ein (auf GitHub unter `Settings -> Manage access`)
** löschen Sie das nicht benötigte Repository (auf GitHub unter `Settings`)
** arbeiten Sie gemeinsam und gleichzeitig an den Aufgaben (Stichwort: Pair-Programming)
** https://www.it-agile.de/wissen/agiles-engineering/pair-programming/[Pair-Programming] heisst insbesondere, dass beide Teammitglieder zu gleichen Teilen aktiv in der Entwickler-Rolle sind. Einem Entwickler lediglich bei seiner Arbeit zuzuschauen ist kein Pair-Programming.
** das Aufteilen und separate Bearbeiten von Teil-Aufgaben ist nicht erwünscht
* Ausdrücklich erlaubt und erwünscht ist, dass Sie sich gegebenenfalls Hilfe holen.
Das Programmierzentrum ist geöffnet und Nachfragen werden zum Beispiel über den im Repository integrierten
Issue Tracker oder per Mail gerne beantwortet.
* Ab Montag, 8.6.2020, 22:00 Uhr, können leider (aus privaten, gesundheitlichen Gründen) keine Fragen mehr beantwortet werden.


=== Bei Problemen mit dem IntelliJ-Setup

Es kommt immer wieder mal vor, dass der Setup des IntelliJ-Projekts nicht auf Anhieb funktioniert oder "plötzlich" nicht mehr funktioniert.

Sie brauchen in so einem Fall NICHT nochmal den Invitation-Link annehmen oder das Projekt via “Check out from Version Control” oder "git clone …" nochmal anlegen.

Statt dessen ist es am besten den IntelliJ-Setup neu generieren zu lassen. Dazu verwendet man den File `build.gradle`, der eine komplette und IDE-unabhängige Projektbeschreibung enthält.

Die einzelnen Schritte:

* Schliessen Sie alle geöffneten Projekte (`File -> Close Project`)
* Wählen Sie “OPEN”
* Es erscheint ein Finder-Fenster mit dem Sie zu ihrem Projekt navigieren.
* Dort wählen Sie den File `build.gradle` aus.
* Beim nächsten Dialog `Open as Project` wählen.
* In der "Project Structure" kontrollieren ob Java 13 ausgewählt ist (und dieser JDK JavaFX enthält).
* In den "Settings" ("Preferences" auf dem Mac) überprüfen, ob für Gradle als "Gradle JVM" der Project-SDK eingestellt ist.

Jetzt sollte der Projekt-Setup korrekt und die beiden `DemoStarter` ausführbar sein.
